<?php

/** @var \Produto\Model\Produto $produto */

$title = 'Deletar Produto';
$url   = $this->url('produto', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Tem certeza que deseja deletar a produto
    "<?= $this->escapeHtml($produto->nome_produto) ?>"?
</p>

<form action="<?= $url ?>" method="post">
<div class="form-group">
    <input type="hidden" name="id" value="<?= (int) $produto->id_produto ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
    <input type="submit" class="btn btn-success" name="del" value="No" />
</div>
</form>