<?php

/** @var \Categoria\Form\CategoriaForm $form */

$title = 'Editar categoria';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$nomeCategoria = $form->get('nome_categoria');
$nomeCategoria->setAttribute('class', 'form-control');
$nomeCategoria->setAttribute('placeholder', 'categoria');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('categoria', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?= $this->formLabel($nomeCategoria) ?>
    <?= $this->formElement($nomeCategoria) ?>
    <?= $this->formElementErrors()->render($nomeCategoria, ['class' => 'help-block']) ?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id_categoria_planejamento'));
echo $this->form()->closeTag();
