<?php
$title = 'Categorias';
$this->headTitle($title);
?>

<?php if (!empty($msgErro = $this->params()->fromQuery('msgErro', null))): ?>
    <div class="alert alert-danger" role="alert"><?= $msgErro ?></div>
<?php endif ?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('categoria', ['action' => 'add']) ?>">Nova categoria</a>
</p>

<table class="table">
    <tr>
        <th>Categoria</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($categorias as $categoria) : ?>
        <tr>
            <td><?= $this->escapeHtml($categoria->nome_categoria) ?></td>
            <td>
                <a href="<?= $this->url('categoria', ['action' => 'edit', 'id' => $categoria->id_categoria_planejamento]) ?>">Editar</a>
                <a href="<?= $this->url('categoria', ['action' => 'delete', 'id' => $categoria->id_categoria_planejamento]) ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>