<div class="row">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Categorias</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="<?= $this->url('categoria')?>">Cadastre agora! &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                <h2 class="card-title">Produtos</h2>
            </div>
            <div class="card-body">
                <p><a class="btn btn-success pull-right" href="<?= $this->url('produto')?>">Cadastre agora! &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
